app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::post('tareas/create','TareaController@save');
Route::post('tareas/{id}/edit','TareaController@update2');
Route::get('obtenerInsumos/{id}','TareaController@getSuppliesByid');

Route::resource('tareas/report','TareaController@report');
Route::resource('lote', 'LoteController');
Route::resource('tareas', 'TareaController');
Route::resource('empleados', 'EmpleadoController');
Route::resource('insumos', 'InsumoController');
Route::resource('productos', 'ProductoController');
Route::resource('labores', 'LaborController');
Route::resource('categoria_empleado', 'Categoria_empleadoController');
Route::resource('categoria_insumos', 'Categoria_insumosController');

Route::get('reporte_empleados','ReporteController@indexEmpleados');
Route::post('reporte_empleados','ReporteController@showEmpleados');


Route::get('reporte_empleados_lapse','ReporteController@indexEmpleadosLapse');
Route::post('reporte_empleados_lapse','ReporteController@showEmpleadosLapse');

Route::get('reporte_insumos','ReporteController@indexInsumos');
Route::post('reporte_insumos','ReporteController@showInsumos');

Route::get('reporte_tarea','ReporteController@indexTarea');
Route::post('reporte_tarea','ReporteController@showTareas');

Route::post('getLabors','ReporteController@showLabores');


Route::get('insumos/{id}/recharge','InsumoController@recharge');
Route::post('insumos/save_recharge/{id}','InsumoController@save_recharge');

Route::get('dropdown', function(){
	$id = Request::input('option');
	$insumos = Categoria_Insumo::find($id)->insumos;
	return $insumos->lists('id', 'descripcion');
});
Route::resource('usuario','UsuarioController@updatePassword');
Route::resource('usuarios','UsuarioController');

Route::get('getSupplies/{id}','TareaController@getDataTableSupplies');
Route::get('getEmployees/{id}','TareaController@getEmployees');
//Para llenar tabla de tareas

Route::post('getInfo','ReporteController@create');

Route::post('obtenerReporte','TareaController@getInfo');

// Authentication routes...

Route::get('/', [
	'uses'=>'Auth\AuthController@index',
	'as' => 'login_principal'
	]);

Route::get('login', [
	'uses'=>'Auth\AuthController@getLogin',
	'as' => 'login'
	]);

Route::post('login', 'Auth\AuthController@postLogin');

Route::get('logout', [
	'uses'=>'Auth\AuthController@getLogout',
	'as'=>'logout'
	]);
/*/// Authentication routes...
Route::get('/', [
	'uses'=>'Auth\AuthController@index',
	'as' => 'login_principal'
	]);

Route::get('login', function()
{

	if (Auth::check())
	{
		return redirect ('home');

	}
	//return redirect('login_principal');
	return view('auth.login');

});


Route::post('login', 'Auth\AuthController@postLogin');

Route::get('logout', [
	'uses'=>'Auth\AuthController@getLogout',
	'as'=>'logout'
	]);
*/
// Registration routes...
Route::get('register', [
	'uses'=>'UsuarioController@create',
	'as'=>'register'
	]);

Route::get('home', [
	'uses'=>'HomeController@index',
	'as' => 'home'
	]);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('obtenerInsumos/{id}','TareaController@getSuppliesByid');

Route::get('tareas', 'TareaController@index')->name('tareas');
Route::get('tareas/create', 'TareaController@create')->name('tareas.create');
Route::post('tareas/create','TareaController@save')->name('tareas.create');
Route::post('tareas/{id}/edit','TareaController@update2')->name('tareas.edit');
Route::get('tareas/{id}/edit','TareaController@edit')->name('tareas.edit');
Route::delete('/tareas/{id}','TareaController@destroy');

Route::resource('empleados', 'EmpleadoController');
Route::resource('insumos', 'InsumoController');
Route::resource('productos', 'ProductoController');
Route::resource('labores', 'LaborController');
Route::resource('unidad', 'UnidadController');
Route::resource('categoria_empleado', 'Categoria_empleadoController');
Route::resource('categoria_insumos', 'Categoria_insumosController');
Route::resource('lote', 'LoteController');

//reporte empleado -semanal
Route::get('reporte_empleados','ReporteController@indexEmpleados');
Route::post('reporte_empleados','ReporteController@showEmpleados');

Route::resource('tareas/report','TareaController@report');
//reporte empleado -rango de fecha
Route::get('reporte_empleados_lapse','ReporteController@indexEmpleadosLapse');
Route::post('reporte_empleados_lapse','ReporteController@showEmpleadosLapse');

Route::get('reporte_insumos','ReporteController@indexInsumos');
Route::post('reporte_insumos','ReporteController@showInsumos');

//reporte de tareas
Route::get('reporte_tarea','ReporteController@indexTarea');
Route::post('reporte_tarea','ReporteController@showTareas');

Route::post('getLabors','ReporteController@showLabores');


Route::get('insumos/{id}/recharge','InsumoController@recharge');
Route::post('insumos/save_recharge/{id}','InsumoController@save_recharge');

Route::get('dropdown', function(){
	$id = Request::input('option');
	$insumos = Categoria_Insumo::find($id)->insumos;
	return $insumos->lists('id', 'descripcion');
});
Route::put('usuarios/changepass/','UsuarioController@updatePassword')->name('changepass');
Route::resource('usuarios','UsuarioController');

Route::get('getSupplies/{id}','TareaController@getDataTableSupplies');
Route::get('getEmployees/{id}','TareaController@getEmployees')->name('getEmployees');

//Para llenar tabla de tareas

Route::post('getInfo','ReporteController@create');

Route::post('obtenerReporte','TareaController@getInfo');



Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::post('login', 'Auth\LoginController@authenticate')->name('login');
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('register', 'Auth\RegisterController@registerUser')->name('register');

resources/views/labores/create.blade.php
@extends('layouts.master')
@section('content')
<div class="panel panel-default col-md-8 col-md-offset-2 pa">
	<div class="panel-heading">Nueva Labor</div>
	<div class="panel-body">
		@if (count($errors) > 0)
		<div class="alert alert-danger">
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<ul>
				<li>El nombre de la labor esta en uso, intente de nuevo.</li>
			</ul>
		</div>
		@endif
		<form action='/labores' method="POST">
			<input type="hidden" name="_token" value="{{ csrf_token() }}">
			<label for="cedula">Nombre labor:</label>
			<input class="form-control" required="required" name="descripcion" type="text" id="descripcion">
			<br>
<<<<<<< HEAD
			<a href="{{ URL::asset('/labores') }}"><button type="button" class="btn btn-warning col-md-4 pull-right" >Volver</button></a>
			{!! Form::submit('Crear', ['class' => 'btn btn-primary col-md-4 pull-right']) !!}
		</form>
	</div>

=======
			{!! Form::submit('Crear', ['class' => 'btn btn-primary col-md-4 pull-right']) !!}
		</form>
	</div>
	<div class="col-xs-12">
		<a href="{{ URL::asset('/labores') }}"><button class="btn btn-warning col-md-4 pull-right" >Volver</button></a><br>
	</div>
>>>>>>> f067d63699a17b92d6acba30915213898a64db5c
</div>
@endsection

resources/views/labores/edit.blade.php
@extends('layouts.master')
@section('content')
<div class="panel panel-default col-md-7 col-md-offset-2 pa">
<div class="panel-heading">Editar Labor</div>
	<div class="panel-body">
		@if (count($errors) > 0)
		<div class="alert alert-danger">
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<ul>
				<li>El nombre de la labor esta en uso, intente de nuevo.</li>
			</ul>
		</div>
		@endif
		<form action='/labores/{{$labor->id}}' method="POST">
			<input type="hidden" name="_method" value="PUT">
			<input type="hidden" name="_token" value="{{ csrf_token() }}">
			<label for="cedula">Nombre de Labor:</label>
			<input class="form-control" required="required" name="descripcion" type="text" id="descripcion" value="{{$labor->descripcion}}">
			<br>
<<<<<<< HEAD
			<a href="{{ URL::asset('/labores') }}"><button type="button"class="btn btn-warning col-md-4 pull-right" >Volver</button></a>
			{!! Form::submit('Guardar', ['class' => 'btn btn-primary col-md-4 pull-right']) !!}
		</form>
	</div>

=======
			{!! Form::submit('Guardar', ['class' => 'btn btn-primary col-md-4 pull-right']) !!}
		</form>
	</div>
	<div class="col-xs-12">
		<a href="{{ URL::asset('/labores') }}"><button class="btn btn-warning col-md-4 pull-right" >Volver</button></a>
	</div>
>>>>>>> f067d63699a17b92d6acba30915213898a64db5c
</div>
@endsection

resources/views/labores/index.blade.php
@extends('layouts.master')
@section('style')
<link rel="stylesheet" type="text/css" href="/assets/DataTables/media/css/jquery.dataTables.min.css">
@endsection()
@section('content')
<div class="panel panel-default">
  <div class="panel-heading pull-right"><a href="{{ route('labores.create') }}" class="btn btn-primary">Agregar nueva Labor</a></div>
  <div class="panel-heading">Mantenimiento Labores</div>
  <div class="panel-body">
    <table id="example" class="display" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Descripcion</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>Descripcion</th>
          <th>Acciones</th>
        </tr>
      </tfoot>
      <tbody>
        @foreach ($labores as $labor)
        <tr>
          <td>{{$labor->descripcion}}</td>
          <td>
            <a href='/labores/{{$labor->id}}/edit'><button class="btn btn-primary" data-toggle="tooltip" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></button></a>
            <form action="/labores/{{$labor->id}}" method="POST" style="display:inline">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <input type="hidden" name="_method" value="DELETE">
              <button type="submit" class="btn btn-danger" title="Eliminar">
                <i class="glyphicon glyphicon-trash"></i>
              </button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@endsection
@section('table')
<script src="/assets/DataTables/media/js/jquery.dataTables.js"></script>
<script src="/assets/js/table.js"></script>
@endsection